export const UPDATE_INTERVAL = 5000;
export const DEFAULT_ARRIVAL_TIME = 10;
export var systemSetting = {};

export const NOTIFICATION_TYPE_ORDER_CREATED = '0';
export const NOTIFICATION_TYPE_ORDER_ASSIGNED = '1';
export const NOTIFICATION_TYPE_ORDER_CANCEL = '2';
export const NOTIFICATION_TYPE_ORDER_CANCEL_BY_DELIVERYMAN = '3';
export const NOTIFICATION_TYPE_ORDER_PROCESSING = '4';
export const NOTIFICATION_TYPE_ORDER_COMPLETED = '5';
export const NOTIFICATION_TYPE_ORDER_FEEDBACK = '6';
export const NOTIFICATION_TYPE_ORDER_CANNOT_CREATE = '7';
export const NOTIFICATION_TYPE_ARRIVE_TO_COLLECT = '8';
export const NOTIFICATION_TYPE_ARRIVE_TO_DELIVER = '9';