import React, { useState, useCallback, useEffect } from 'react';
import { ActivityIndicator, Alert, StyleSheet, Text, View } from "react-native"
import Icons from "react-native-vector-icons/Ionicons";

import GlobalStyles from "../../styles/style"
import GoDeliveryColors from "../../styles/colors"
import Action from '../../service';
import MenuButton from '../../components/MenuButton';
import PrimaryButton from '../../components/PrimaryButton';
import OTPInputView from '@twotalltotems/react-native-otp-input';
import TwillioService from '../../service/TwillioService';

const OrderValidate = ({ navigation, route }: {
    navigation: any,
    route: any,
}) => {
    const { orderID, phone } = route.params;
    const [activityIndicator, setActivityIndicator] = useState(false);
    const [value, setValue] = useState('');

    const handleReceive = async () => {
        setActivityIndicator(true);
        if (await TwillioService.checkVerification(phone, value)) {
            Action.order.receiveGoods({ orderID: orderID })
                .then((res) => {
                    const response = res.data;
                    setActivityIndicator(false);
                    navigation.navigate("OrderHome");
                }).catch((err) => {
                    console.log("error: ", err);
                    setActivityIndicator(false);
                })
        } else {
            setActivityIndicator(false);
            Alert.alert("Validation failed. Try again.");
        }
    }

    return (
        <View style={[GlobalStyles.container]}>
            <View style={styles.topStatusBar}>
                <Text style={[GlobalStyles.headerTitle, { color: GoDeliveryColors.white }]}>DELIVERY CODE</Text>
            </View>
            <MenuButton navigation={navigation} />
            <View style={{ flex: 1, flexDirection: 'column', justifyContent: 'space-between' }}>
                <View style={{ backgroundColor: '#fcf2ab', padding: 20, flexDirection: 'row', gap: 10, marginHorizontal: 20, borderRadius: 20, marginTop: 60, justifyContent: 'center', alignItems: 'center' }}>
                    <Icons name="warning-outline" size={50} color={"#fec200"} />
                    <Text style={[GlobalStyles.textBold, { flex: 1 }]}>Before delivering the package to the receiver, please validate it by entering the OTP code generated by our System.</Text>
                </View>
                <View style={{ flex: 1, justifyContent: 'space-between', marginVertical: 30, paddingHorizontal: 20 }}>
                    <View style={{ width: '80%', height: 60, justifyContent: 'center', alignItems: 'center', alignSelf: 'center' }}>
                        <OTPInputView
                            autoFocusOnLoad={false}
                            pinCount={6}
                            style={{ borderColor: 'black', }}
                            code={value}
                            onCodeChanged={code => setValue(code)}
                            onCodeFilled={code => setValue(code)}
                            codeInputFieldStyle={{
                                borderColor: GoDeliveryColors.primary,
                                borderRadius: 100,
                                color: GoDeliveryColors.secondary,
                            }} />
                    </View>
                    <PrimaryButton buttonText='VALIDATE' handler={handleReceive} />
                </View>
            </View>
            {
                activityIndicator && <ActivityIndicator size="large" style={{ position: 'absolute', bottom: 70, alignSelf: 'center' }} />
            }
        </View>
    )
}

const styles = StyleSheet.create({
    topStatusBar: {
        flexDirection: 'row',
        backgroundColor: GoDeliveryColors.primary,
        width: '100%',
        height: 60,
        alignItems: 'center',
        paddingLeft: 80,
        justifyContent: 'space-between',
        paddingRight: 20,
    },
})

export default OrderValidate;